// =============================================================================
// ByteSpace Landing Page — Static Data Constants
// =============================================================================

// -----------------------------------------------------------------------------
// Navigation
// -----------------------------------------------------------------------------
export const NAV_LINKS = [
  { label: "Home", href: "/", active: true },
  { label: "Courses", href: "/courses", active: false },
  { label: "Creators", href: "/creators", active: false },
] as const;

export const NAV_ACTIONS = [
  { label: "Sign In", href: "/signin" },
  { label: "Join Us", href: "/join" },
] as const;

// -----------------------------------------------------------------------------
// Authentication Configuration & Copy
// -----------------------------------------------------------------------------
export const AUTH_CONTENT = {
  register: {
    badge: "Create an Account",
    title: "Welcome to ByteSpace",
    heroTitle: "Sign up and come in",
    heroDescription:
      "The registration process is straightforward, uncomplicated, and efficient, allowing users to sign up quickly, easily, and at no cost",
    submitText: "Continue",
    switchPrompt: "Already have an account?",
    switchLinkText: "Login",
    switchHref: "/signin",
  },
  login: {
    badge: "Sign In",
    title: "Welcome Back",
    heroTitle: "Sign in with ease",
    heroDescription:
      "Experience a seamless and efficient sign-in process that grants you instant access to a world of knowledge.",
    submitText: "Sign In",
    switchPrompt: "New user?",
    switchLinkText: "Create an account",
    switchHref: "/join",
  },
} as const;

// -----------------------------------------------------------------------------
// Partner Logos
// -----------------------------------------------------------------------------
export const PARTNER_LOGOS = [
  { src: "/partner/partner-one.svg", alt: "Partner One", width: 167, height: 41 },
  { src: "/partner/partner-two.svg", alt: "Partner Two", width: 168, height: 41 },
  { src: "/partner/partner-3.svg", alt: "Partner Three", width: 168, height: 41 },
  { src: "/partner/partner-four.svg", alt: "Partner Four", width: 168, height: 41 },
  { src: "/partner/partner-five.svg", alt: "Partner Five", width: 169, height: 42 },
] as const;

// -----------------------------------------------------------------------------
// Course Tab Categories
// -----------------------------------------------------------------------------
export const COURSE_TABS = [
  { label: "Featured", active: true },
  { label: "Music", active: false },
  { label: "Drawing & Painting", active: false },
  { label: "Marketing", active: false },
  { label: "Animation", active: false },
  { label: "Social Media", active: false },
  { label: "UI/UX Design", active: false },
  { label: "Creative Marketing", active: false },
  { label: "Digital Illustration", active: false },
  { label: "Film & Video", active: false },
  { label: "Crafts", active: false },
  { label: "Freelance & Entrepreneurship", active: false },
  { label: "Graphic Design", active: false },
  { label: "Photography", active: false },
  { label: "Productivity", active: false },
  { label: "Web Development", active: false },
  { label: "Data Science", active: false },
  { label: "Cooking", active: false },
] as const;

// -----------------------------------------------------------------------------
// Landing Page Courses (6 items)
// -----------------------------------------------------------------------------
export const COURSES = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
  },
  {
    id: 2,
    title: "Build Digital Asset",
    author: "purepearl studio",
    image: "/courses/courses-two.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
  },
  {
    id: 3,
    title: "the Power of Big Data",
    author: "purepearl studio",
    image: "/courses/courses-three.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
  },
  {
    id: 4,
    title: "Balancing Productivity and Self-Care",
    author: "purepearl studio",
    image: "/courses/courses-four.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
  },
  {
    id: 5,
    title: "Mastering Money Management",
    author: "purepearl studio",
    image: "/courses/courses-five.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
  },
  {
    id: 6,
    title: "From Idea to Startup Success",
    author: "purepearl studio",
    image: "/courses/courses-six.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
  },
] as const;

// -----------------------------------------------------------------------------
// Courses Page Tabs (Exact Figma Categories)
// -----------------------------------------------------------------------------
export const COURSES_PAGE_TABS = [
  "Featured",
  "Music",
  "Drawing & Painting",
  "Marketing",
  "Animation",
  "Social Media",
  "UI/UX Design",
  "Creative Marketing",
  "Cooking",
] as const;

// -----------------------------------------------------------------------------
// All Courses Data (Rich dataset for Courses page with multiple pages)
// -----------------------------------------------------------------------------
export const ALL_COURSES = [
  // Page 1
  {
    id: 1,
    title: "Learn Figma from Basic",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "UI/UX Design",
  },
  {
    id: 2,
    title: "Build Digital Asset",
    author: "purepearl studio",
    image: "/courses/courses-two.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Marketing",
  },
  {
    id: 3,
    title: "the Power of Big Data",
    author: "purepearl studio",
    image: "/courses/courses-three.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Drawing & Painting",
  },
  {
    id: 4,
    title: "Balancing Productivity and Self-Care",
    author: "purepearl studio",
    image: "/courses/courses-four.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Music",
  },
  {
    id: 5,
    title: "Mastering Money Management",
    author: "purepearl studio",
    image: "/courses/courses-five.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Creative Marketing",
  },
  {
    id: 6,
    title: "From Idea to Startup Success",
    author: "purepearl studio",
    image: "/courses/courses-six.jpg",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Animation",
  },

  // Page 2
  {
    id: 7,
    title: "Advanced Design Systems with Figma",
    author: "DesignCraft Studio",
    image: "/courses/courses-one.jpg",
    lessons: 24,
    duration: "3 hours 45 mins",
    comments: 84,
    level: "Advanced",
    students: 42,
    price: 39,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "UI/UX Design",
  },
  {
    id: 8,
    title: "Full Funnel Growth Marketing",
    author: "GrowthWave Media",
    image: "/courses/courses-two.jpg",
    lessons: 19,
    duration: "2 hours 30 mins",
    comments: 41,
    level: "Intermediate",
    students: 31,
    price: 29,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Marketing",
  },
  {
    id: 9,
    title: "Oil Painting Techniques & Light",
    author: "Artistry Collective",
    image: "/courses/courses-three.jpg",
    lessons: 15,
    duration: "1 hour 55 mins",
    comments: 36,
    level: "Beginner",
    students: 19,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Drawing & Painting",
  },
  {
    id: 10,
    title: "Electronic Music Production with Ableton",
    author: "SoundWave Academy",
    image: "/courses/courses-four.jpg",
    lessons: 28,
    duration: "4 hours 10 mins",
    comments: 92,
    level: "Intermediate",
    students: 54,
    price: 35,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Music",
  },
  {
    id: 11,
    title: "Viral TikTok & Reels Marketing",
    author: "SocialSpark Studio",
    image: "/courses/courses-five.jpg",
    lessons: 14,
    duration: "1 hour 45 mins",
    comments: 63,
    level: "Beginner",
    students: 38,
    price: 20,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Social Media",
  },
  {
    id: 12,
    title: "Art of Italian Pasta Making",
    author: "Chef Giovanni",
    image: "/courses/courses-six.jpg",
    lessons: 12,
    duration: "1 hour 30 mins",
    comments: 48,
    level: "Beginner",
    students: 29,
    price: 18,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Cooking",
  },

  // Page 3
  {
    id: 13,
    title: "Mobile App UX Research & Testing",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 21,
    duration: "2 hours 50 mins",
    comments: 72,
    level: "Intermediate",
    students: 35,
    price: 30,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "UI/UX Design",
  },
  {
    id: 14,
    title: "2D Character Animation in After Effects",
    author: "MotionBox Lab",
    image: "/courses/courses-two.jpg",
    lessons: 22,
    duration: "3 hours 15 mins",
    comments: 55,
    level: "Intermediate",
    students: 27,
    price: 34,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Animation",
  },
  {
    id: 15,
    title: "Watercolor Botanical Illustration",
    author: "FloraArts",
    image: "/courses/courses-three.jpg",
    lessons: 16,
    duration: "2 hours 05 mins",
    comments: 39,
    level: "Beginner",
    students: 22,
    price: 24,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Drawing & Painting",
  },
  {
    id: 16,
    title: "Acoustic Guitar for Songwriters",
    author: "MelodyCraft",
    image: "/courses/courses-four.jpg",
    lessons: 18,
    duration: "2 hours 40 mins",
    comments: 67,
    level: "Beginner",
    students: 44,
    price: 27,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Music",
  },
  {
    id: 17,
    title: "Brand Storytelling & Copywriting",
    author: "CreativeEcho",
    image: "/courses/courses-five.jpg",
    lessons: 20,
    duration: "2 hours 20 mins",
    comments: 51,
    level: "Intermediate",
    students: 33,
    price: 28,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Creative Marketing",
  },
  {
    id: 18,
    title: "Artisan Sourdough Baking",
    author: "Baker’s Table",
    image: "/courses/courses-six.jpg",
    lessons: 15,
    duration: "2 hours 10 mins",
    comments: 58,
    level: "Beginner",
    students: 37,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Cooking",
  },

  // Page 4
  {
    id: 19,
    title: "Interactive Prototyping Masterclass",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 25,
    duration: "3 hours 20 mins",
    comments: 89,
    level: "Advanced",
    students: 48,
    price: 45,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "UI/UX Design",
  },
  {
    id: 20,
    title: "SEO & Content Marketing Strategy",
    author: "SearchBoost Pro",
    image: "/courses/courses-two.jpg",
    lessons: 18,
    duration: "2 hours 15 mins",
    comments: 44,
    level: "Intermediate",
    students: 29,
    price: 26,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Marketing",
  },
  {
    id: 21,
    title: "Digital Portrait Painting in Procreate",
    author: "CanvasPro Studio",
    image: "/courses/courses-three.jpg",
    lessons: 19,
    duration: "2 hours 55 mins",
    comments: 61,
    level: "Intermediate",
    students: 36,
    price: 32,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Drawing & Painting",
  },
  {
    id: 22,
    title: "Music Theory & Chord Progressions",
    author: "Harmony House",
    image: "/courses/courses-four.jpg",
    lessons: 16,
    duration: "2 hours 00 mins",
    comments: 53,
    level: "Beginner",
    students: 41,
    price: 24,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Music",
  },
  {
    id: 23,
    title: "3D Motion Graphics with Cinema 4D",
    author: "MotionBox Lab",
    image: "/courses/courses-five.jpg",
    lessons: 30,
    duration: "4 hours 30 mins",
    comments: 104,
    level: "Advanced",
    students: 58,
    price: 49,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Animation",
  },
  {
    id: 24,
    title: "French Pastry & Macaron Perfection",
    author: "Chef Pierre",
    image: "/courses/courses-six.jpg",
    lessons: 14,
    duration: "1 hour 50 mins",
    comments: 62,
    level: "Intermediate",
    students: 39,
    price: 28,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Cooking",
  },

  // Page 5
  {
    id: 25,
    title: "Design Tokens & Tailwind CSS Workflow",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 16,
    duration: "2 hours 10 mins",
    comments: 47,
    level: "Intermediate",
    students: 33,
    price: 29,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "UI/UX Design",
  },
  {
    id: 26,
    title: "Instagram Growth & Personal Branding",
    author: "SocialSpark Studio",
    image: "/courses/courses-two.jpg",
    lessons: 15,
    duration: "1 hour 40 mins",
    comments: 52,
    level: "Beginner",
    students: 45,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Social Media",
  },
  {
    id: 27,
    title: "Creative Ad Campaigns & Visual Copy",
    author: "CreativeEcho",
    image: "/courses/courses-three.jpg",
    lessons: 18,
    duration: "2 hours 25 mins",
    comments: 38,
    level: "Intermediate",
    students: 28,
    price: 31,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Creative Marketing",
  },
  {
    id: 28,
    title: "Traditional Sushi Craft & Knife Skills",
    author: "Chef Kenji",
    image: "/courses/courses-four.jpg",
    lessons: 13,
    duration: "1 hour 45 mins",
    comments: 49,
    level: "Beginner",
    students: 34,
    price: 27,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Cooking",
  },
  {
    id: 29,
    title: "Vocal Recording & Mixing at Home",
    author: "SoundWave Academy",
    image: "/courses/courses-five.jpg",
    lessons: 20,
    duration: "2 hours 45 mins",
    comments: 56,
    level: "Intermediate",
    students: 37,
    price: 33,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Music",
  },
  {
    id: 30,
    title: "Storyboarding & Visual Narrative",
    author: "MotionBox Lab",
    image: "/courses/courses-six.jpg",
    lessons: 17,
    duration: "2 hours 15 mins",
    comments: 43,
    level: "Beginner",
    students: 25,
    price: 26,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Animation",
  },

  // Page 6
  {
    id: 31,
    title: "Figma to Code: Responsive Web Design",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 22,
    duration: "3 hours 10 mins",
    comments: 76,
    level: "Intermediate",
    students: 52,
    price: 38,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "UI/UX Design",
  },
  {
    id: 32,
    title: "Community Building on Discord & Reddit",
    author: "SocialSpark Studio",
    image: "/courses/courses-two.jpg",
    lessons: 14,
    duration: "1 hour 35 mins",
    comments: 39,
    level: "Beginner",
    students: 30,
    price: 20,
    priceLabel: "/lifetime",
    rating: 4.4,
    category: "Social Media",
  },
  {
    id: 33,
    title: "Digital Gouache & Landscape Art",
    author: "Artistry Collective",
    image: "/courses/courses-three.jpg",
    lessons: 18,
    duration: "2 hours 30 mins",
    comments: 47,
    level: "Beginner",
    students: 28,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Drawing & Painting",
  },
  {
    id: 34,
    title: "Email Marketing Automations with Klaviyo",
    author: "GrowthWave Media",
    image: "/courses/courses-four.jpg",
    lessons: 16,
    duration: "2 hours 05 mins",
    comments: 34,
    level: "Intermediate",
    students: 26,
    price: 29,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Marketing",
  },
  {
    id: 35,
    title: "Gourmet Plant-Based Cuisine",
    author: "Chef Elena",
    image: "/courses/courses-five.jpg",
    lessons: 15,
    duration: "2 hours 00 mins",
    comments: 51,
    level: "Beginner",
    students: 32,
    price: 23,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Cooking",
  },
  {
    id: 36,
    title: "Guerrilla Marketing & Growth Hacks",
    author: "CreativeEcho",
    image: "/courses/courses-six.jpg",
    lessons: 19,
    duration: "2 hours 20 mins",
    comments: 65,
    level: "Advanced",
    students: 40,
    price: 36,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Creative Marketing",
  },
  {
    id: 37,
    title: "Typography & Layout Secrets for Web",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 15,
    duration: "2 hours 10 mins",
    comments: 48,
    level: "Intermediate",
    students: 38,
    price: 28,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "UI/UX Design",
  },
  {
    id: 38,
    title: "Performance Ads for E-Commerce",
    author: "GrowthWave Media",
    image: "/courses/courses-two.jpg",
    lessons: 21,
    duration: "2 hours 45 mins",
    comments: 53,
    level: "Advanced",
    students: 44,
    price: 35,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Marketing",
  },
  {
    id: 39,
    title: "Acrylic Landscape Painting for Beginners",
    author: "Artistry Collective",
    image: "/courses/courses-three.jpg",
    lessons: 14,
    duration: "1 hour 50 mins",
    comments: 32,
    level: "Beginner",
    students: 21,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Drawing & Painting",
  },
  {
    id: 40,
    title: "Piano Chords & Ear Training",
    author: "SoundWave Academy",
    image: "/courses/courses-four.jpg",
    lessons: 20,
    duration: "2 hours 35 mins",
    comments: 64,
    level: "Beginner",
    students: 49,
    price: 26,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Music",
  },
  {
    id: 41,
    title: "3D Motion Design with Blender",
    author: "MotionBox Lab",
    image: "/courses/courses-five.jpg",
    lessons: 26,
    duration: "3 hours 50 mins",
    comments: 79,
    level: "Intermediate",
    students: 53,
    price: 42,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Animation",
  },
  {
    id: 42,
    title: "Authentic Thai Cooking at Home",
    author: "Chef Somchai",
    image: "/courses/courses-six.jpg",
    lessons: 16,
    duration: "2 hours 15 mins",
    comments: 57,
    level: "Beginner",
    students: 36,
    price: 24,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Cooking",
  },
  {
    id: 43,
    title: "Design Systems in Code with React",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 23,
    duration: "3 hours 30 mins",
    comments: 68,
    level: "Advanced",
    students: 47,
    price: 45,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "UI/UX Design",
  },
  {
    id: 44,
    title: "YouTube Video Editing & Storytelling",
    author: "SocialSpark Studio",
    image: "/courses/courses-two.jpg",
    lessons: 18,
    duration: "2 hours 25 mins",
    comments: 46,
    level: "Intermediate",
    students: 41,
    price: 29,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Social Media",
  },
  {
    id: 45,
    title: "Modern Ink & Pen Drawing",
    author: "Artistry Collective",
    image: "/courses/courses-three.jpg",
    lessons: 13,
    duration: "1 hour 40 mins",
    comments: 29,
    level: "Beginner",
    students: 23,
    price: 19,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Drawing & Painting",
  },
  {
    id: 46,
    title: "Beatmaking & Drum Programming",
    author: "SoundWave Academy",
    image: "/courses/courses-four.jpg",
    lessons: 17,
    duration: "2 hours 10 mins",
    comments: 52,
    level: "Intermediate",
    students: 38,
    price: 30,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Music",
  },
  {
    id: 47,
    title: "Brand Strategy & Positioning Workshop",
    author: "CreativeEcho",
    image: "/courses/courses-five.jpg",
    lessons: 19,
    duration: "2 hours 40 mins",
    comments: 45,
    level: "Advanced",
    students: 34,
    price: 38,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Creative Marketing",
  },
  {
    id: 48,
    title: "Mastering Mexican Street Food",
    author: "Chef Mateo",
    image: "/courses/courses-six.jpg",
    lessons: 14,
    duration: "1 hour 55 mins",
    comments: 61,
    level: "Beginner",
    students: 42,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Cooking",
  },
  {
    id: 49,
    title: "Figma Variables & Advanced Components",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 20,
    duration: "2 hours 55 mins",
    comments: 82,
    level: "Intermediate",
    students: 51,
    price: 36,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "UI/UX Design",
  },
  {
    id: 50,
    title: "Copywriting for High-Converting Landing Pages",
    author: "GrowthWave Media",
    image: "/courses/courses-two.jpg",
    lessons: 16,
    duration: "2 hours 05 mins",
    comments: 37,
    level: "Beginner",
    students: 28,
    price: 25,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Marketing",
  },
  {
    id: 51,
    title: "Charcoal Sketching Masterclass",
    author: "CanvasPro Studio",
    image: "/courses/courses-three.jpg",
    lessons: 15,
    duration: "1 hour 50 mins",
    comments: 34,
    level: "Beginner",
    students: 20,
    price: 20,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Drawing & Painting",
  },
  {
    id: 52,
    title: "Guitar Soloing & Improvisation",
    author: "MelodyCraft",
    image: "/courses/courses-four.jpg",
    lessons: 22,
    duration: "3 hours 00 mins",
    comments: 71,
    level: "Advanced",
    students: 43,
    price: 34,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Music",
  },
  {
    id: 53,
    title: "LinkedIn Thought Leadership & B2B Growth",
    author: "SocialSpark Studio",
    image: "/courses/courses-five.jpg",
    lessons: 14,
    duration: "1 hour 30 mins",
    comments: 42,
    level: "Intermediate",
    students: 35,
    price: 26,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Social Media",
  },
  {
    id: 54,
    title: "Art of Japanese Ramen from Scratch",
    author: "Chef Kenji",
    image: "/courses/courses-six.jpg",
    lessons: 18,
    duration: "2 hours 40 mins",
    comments: 86,
    level: "Intermediate",
    students: 62,
    price: 32,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Cooking",
  },
  {
    id: 55,
    title: "UX Micro-interactions & Micro-animations",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 17,
    duration: "2 hours 15 mins",
    comments: 63,
    level: "Intermediate",
    students: 39,
    price: 32,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "UI/UX Design",
  },
  {
    id: 56,
    title: "Brand Identity Design Systems",
    author: "CreativeEcho",
    image: "/courses/courses-two.jpg",
    lessons: 24,
    duration: "3 hours 20 mins",
    comments: 58,
    level: "Advanced",
    students: 46,
    price: 40,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Creative Marketing",
  },
  {
    id: 57,
    title: "Colored Pencil Realistic Drawing",
    author: "FloraArts",
    image: "/courses/courses-three.jpg",
    lessons: 16,
    duration: "2 hours 10 mins",
    comments: 41,
    level: "Beginner",
    students: 25,
    price: 23,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Drawing & Painting",
  },
  {
    id: 58,
    title: "Film Scoring & Cinematic Composition",
    author: "Harmony House",
    image: "/courses/courses-four.jpg",
    lessons: 25,
    duration: "3 hours 45 mins",
    comments: 83,
    level: "Advanced",
    students: 55,
    price: 48,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Music",
  },
  {
    id: 59,
    title: "Stop Motion Animation Fundamentals",
    author: "MotionBox Lab",
    image: "/courses/courses-five.jpg",
    lessons: 15,
    duration: "2 hours 05 mins",
    comments: 39,
    level: "Beginner",
    students: 28,
    price: 27,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Animation",
  },
  {
    id: 60,
    title: "Classic Italian Pizza & Focaccia Masterclass",
    author: "Chef Giovanni",
    image: "/courses/courses-six.jpg",
    lessons: 13,
    duration: "1 hour 40 mins",
    comments: 67,
    level: "Beginner",
    students: 48,
    price: 24,
    priceLabel: "/lifetime",
    rating: 4.9,
    category: "Cooking",
  },
  {
    id: 61,
    title: "User Journey Mapping & Information Architecture",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 18,
    duration: "2 hours 30 mins",
    comments: 54,
    level: "Intermediate",
    students: 37,
    price: 30,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "UI/UX Design",
  },
  {
    id: 62,
    title: "Content Marketing Playbook for Creators",
    author: "GrowthWave Media",
    image: "/courses/courses-two.jpg",
    lessons: 15,
    duration: "2 hours 00 mins",
    comments: 36,
    level: "Beginner",
    students: 29,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Marketing",
  },
  {
    id: 63,
    title: "Pastel Drawing & Expressionist Color",
    author: "Artistry Collective",
    image: "/courses/courses-three.jpg",
    lessons: 14,
    duration: "1 hour 45 mins",
    comments: 28,
    level: "Beginner",
    students: 19,
    price: 20,
    priceLabel: "/lifetime",
    rating: 4.5,
    category: "Drawing & Painting",
  },
  {
    id: 64,
    title: "Audio Mastering Techniques in Logic Pro",
    author: "SoundWave Academy",
    image: "/courses/courses-four.jpg",
    lessons: 21,
    duration: "2 hours 50 mins",
    comments: 62,
    level: "Advanced",
    students: 40,
    price: 39,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Music",
  },
  {
    id: 65,
    title: "Short-Form Video Strategy (Reels & Shorts)",
    author: "SocialSpark Studio",
    image: "/courses/courses-five.jpg",
    lessons: 16,
    duration: "1 hour 50 mins",
    comments: 48,
    level: "Beginner",
    students: 36,
    price: 24,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Social Media",
  },
  {
    id: 66,
    title: "Indian Curry & Spice Blending Essentials",
    author: "Chef Priya",
    image: "/courses/courses-six.jpg",
    lessons: 15,
    duration: "2 hours 10 mins",
    comments: 59,
    level: "Beginner",
    students: 38,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Cooking",
  },
  {
    id: 67,
    title: "Design Strategy & Client Pitching",
    author: "purepearl studio",
    image: "/courses/courses-one.jpg",
    lessons: 16,
    duration: "2 hours 15 mins",
    comments: 49,
    level: "Intermediate",
    students: 32,
    price: 33,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "UI/UX Design",
  },
  {
    id: 68,
    title: "E-Commerce Conversion Rate Optimization",
    author: "GrowthWave Media",
    image: "/courses/courses-two.jpg",
    lessons: 20,
    duration: "2 hours 40 mins",
    comments: 51,
    level: "Advanced",
    students: 39,
    price: 38,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Marketing",
  },
  {
    id: 69,
    title: "Modern Gouache Botanicals & Patterns",
    author: "FloraArts",
    image: "/courses/courses-three.jpg",
    lessons: 15,
    duration: "1 hour 55 mins",
    comments: 35,
    level: "Beginner",
    students: 24,
    price: 22,
    priceLabel: "/lifetime",
    rating: 4.6,
    category: "Drawing & Painting",
  },
  {
    id: 70,
    title: "Singer-Songwriter Vocal Production",
    author: "MelodyCraft",
    image: "/courses/courses-four.jpg",
    lessons: 18,
    duration: "2 hours 30 mins",
    comments: 58,
    level: "Intermediate",
    students: 41,
    price: 29,
    priceLabel: "/lifetime",
    rating: 4.7,
    category: "Music",
  },
  {
    id: 71,
    title: "Visual Storytelling in Motion Design",
    author: "MotionBox Lab",
    image: "/courses/courses-five.jpg",
    lessons: 22,
    duration: "3 hours 10 mins",
    comments: 66,
    level: "Intermediate",
    students: 44,
    price: 37,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Animation",
  },
  {
    id: 72,
    title: "Mediterranean Mezze & Tapas Cooking",
    author: "Chef Elena",
    image: "/courses/courses-six.jpg",
    lessons: 14,
    duration: "1 hour 50 mins",
    comments: 53,
    level: "Beginner",
    students: 35,
    price: 23,
    priceLabel: "/lifetime",
    rating: 4.8,
    category: "Cooking",
  },
] as const;

// -----------------------------------------------------------------------------
// Explore Categories (larger cards)
// -----------------------------------------------------------------------------
export const EXPLORE_CATEGORIES = [
  { name: "Design", icon: "Pen" as const },
  { name: "Development", icon: "PhoneCode" as const },
  { name: "IT & Software", icon: "Laptop" as const },
  { name: "Business", icon: "Organization" as const },
  { name: "Marketing", icon: "AnyShare" as const },
  { name: "Photography", icon: "Photography" as const },
] as const;

// -----------------------------------------------------------------------------
// Growth Stats
// -----------------------------------------------------------------------------
export const GROWTH_STATS = [
  { value: "12K", label: "Students" },
  { value: "70+", label: "Courses" },
  { value: "16", label: "Creators" },
] as const;

// -----------------------------------------------------------------------------
// Creator Features
// -----------------------------------------------------------------------------
export const CREATOR_FEATURES = [
  "Share Your Expertise",
  "Monetize Your Passion",
  "Flexibility and Autonomy",
  "Build a Community",
] as const;

// -----------------------------------------------------------------------------
// Testimonials
// -----------------------------------------------------------------------------
export const TESTIMONIALS = [
  {
    quote:
      "ByteSpace transformed my design career. The courses are practical, concise, and taught by genuine industry experts.",
    name: "Alex Rivera",
    role: "Senior Product Designer",
    avatar: "/avatar/avatar-one.png",
  },
  {
    quote:
      "I was able to launch my digital product business in under two months thanks to the actionable blueprints here.",
    name: "Samantha Lee",
    role: "Indie Creator & Founder",
    avatar: "/avatar/avatar-two.png",
  },
  {
    quote:
      "The community and bite-sized learning approach makes it so easy to stay consistent alongside a busy full-time job.",
    name: "Marcus Chen",
    role: "Growth Engineer",
    avatar: "/avatar/avatar-three.png",
  },
] as const;

// -----------------------------------------------------------------------------
// Footer Links
// -----------------------------------------------------------------------------
export const FOOTER_BROWSE_COL1 = [
  "Featured Courses",
  "Featured Categories",
  "Business",
  "IT",
  "Design",
] as const;

export const FOOTER_BROWSE_COL2 = [
  "Development",
  "Marketing",
  "Photography",
  "Finance",
  "Sport",
] as const;

export const FOOTER_PLATFORM = [
  "Become a Creator",
  "Affiliate Program",
  "Contact",
  "Help",
  "About",
] as const;

export const FOOTER_LEGAL = [
  "Privacy Policy",
  "Terms of Service",
  "Cookies Settings",
] as const;

// -----------------------------------------------------------------------------
// Course Details Data Types & Defaults (Figma node 55:4066)
// -----------------------------------------------------------------------------
export interface CourseDetailLesson {
  number: string;
  title: string;
  duration: string;
}

export interface CourseDetailData {
  id: number;
  title: string;
  subtitle: string;
  author: string;
  rating: number;
  reviewsCount: number;
  studentsCount: number;
  level: string;
  videoPreview: string;
  description: string[];
  sneakPeekImages: string[];
  keyPoints: string[];
  lessonsCount: number;
  totalDuration: string;
  lessons: CourseDetailLesson[];
  moreVideosCount: number;
  enrollPitch: string;
  price: number;
  priceLabel: string;
  includes: string[];
  creator: {
    name: string;
    role: string;
    avatar: string;
    bio: string;
  };
}

export const DEFAULT_COURSE_DETAIL: CourseDetailData = {
  id: 2,
  title: "Build Digital Asset: A Comprehensive Guide",
  subtitle: "Unlock the Power of Digital Creation with Expert Guidance",
  author: "purepearl studio",
  rating: 4.8,
  reviewsCount: 172,
  studentsCount: 199,
  level: "Intermediate",
  videoPreview: "/course-details/video-preview.png",
  description: [
    'Embark on an enlightening exploration into the world of digital creation with our comprehensive course, "Build Digital Assets: A Comprehensive Guide." This transformative learning experience invites you to delve deep into the intricacies of crafting impactful digital content. From laying the groundwork with foundational concepts to mastering advanced techniques, this guide is meticulously curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.',
    "In the initial modules, you'll establish a solid foundation by immersing yourself in the foundational concepts that form the backbone of digital asset creation. Understand the fundamental elements that constitute compelling digital content and gain proficiency in leveraging these elements to communicate effectively in the digital realm.",
    "As you progress through the course, you'll ascend to higher levels of expertise, delving into the nuances of design principles that drive impactful creations. Uncover the secrets behind effective visual communication, exploring color theory, typography, and layout strategies that elevate your digital assets to new heights. Engage in hands-on exercises that reinforce your understanding, allowing you to apply these principles in practical scenarios.",
  ],
  sneakPeekImages: [
    "/course-details/sneak-peek-1.png",
    "/course-details/sneak-peek-2.png",
    "/course-details/sneak-peek-3.png",
    "/course-details/sneak-peek-4.png",
  ],
  keyPoints: [
    "Foundational Concepts",
    "Design Principles Mastery",
    "Advanced Techniques in Digital Creation",
    "Project Showcase and Critique",
    "Optimizing for Various Platforms",
    "Digital Asset Management Best Practices",
    "Monetization Strategies",
    "Capstone Project: Building Your Portfolio",
  ],
  lessonsCount: 112,
  totalDuration: "24 hours",
  lessons: [
    {
      number: "01",
      title: "Introduction to Digital Assets",
      duration: "12 mins",
    },
    {
      number: "02",
      title: "Design Principles for Impacts",
      duration: "21 mins",
    },
    {
      number: "03",
      title: "Advanced Techniques in Digital Creation",
      duration: "16 mins",
    },
  ],
  moreVideosCount: 99,
  enrollPitch: "Ready to Dive In? Enroll Now and Start Building Your Digital Future!",
  price: 25,
  priceLabel: "/lifetime",
  includes: [
    "Learning Resources",
    "Quality Lesson Videos",
    "Certificate of Completion",
    "Private Consultation",
  ],
  creator: {
    name: "PurePearl Studio",
    role: "Professional Creator",
    avatar: "/course-details/creator-avatar.png",
    bio: "Ready to Dive In? Enroll Now and Start Building Your Digital Future!",
  },
};

export function getCourseById(id: string | number): CourseDetailData {
  const numericId = Number(id);
  const found = ALL_COURSES.find((c) => c.id === numericId);

  if (!found) {
    return DEFAULT_COURSE_DETAIL;
  }

  return {
    ...DEFAULT_COURSE_DETAIL,
    id: found.id,
    title: found.id === 2 ? DEFAULT_COURSE_DETAIL.title : `${found.title}: A Comprehensive Guide`,
    author: found.author,
    price: found.price,
    priceLabel: found.priceLabel,
    rating: found.rating || DEFAULT_COURSE_DETAIL.rating,
    level: found.level,
    creator: {
      ...DEFAULT_COURSE_DETAIL.creator,
      name: found.author.replace(/^(.)|\s+(.)/g, (c) => c.toUpperCase()),
    },
  };
}
